version: "3.8"

services:

  devoreve:
    image: reenjii/devenv
    restart: unless-stopped
    build: ./devenv
    container_name: devenv
    working_dir: /home/developer
    networks:
      - devenv-network
    ports:
      - "4222:22"      # ssh
      - "80:8080"      # http
      - "10000:10000"  # service

    volumes:
      # Persistent home folder
      - type: bind
        source: /home/ubuntu/devenv
        target: /home/developer
      # Bind docker socket to be able to call docker daemon from inside devenv
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock

  redis:
    image: redis:6.2-alpine
    restart: unless-stopped
    container_name: redis
    networks:
      - devenv-network
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - redisdata:/data

# Volumes
volumes:
  redisdata:
    driver: local

# Custom network
networks:
  devenv-network:
    driver: bridge
    name: devenv-network
